# https://github.com/apps/welcome
newIssueWelcomeComment: >
  Thanks for reporting your first contribution during the [Jenkins UI/UX Online Hackathon](https://www.jenkins.io/events/online-hackfest/2020-uiux/)!
  Be sure to follow the issue template, we will need it for the summary report.
  We also invite you to share your contribution experience in social media, please use the `#JenkinsIsTheWay` hashtag!

  [![Jenkins Is The Way](https://github.com/jenkinsci/ui-ux-hackfest-2020/blob/master/img/jenkins-is-the-way.png?raw=true)](https://www.jenkins.io/events/online-hackfest/2020-uiux/)
  
